### PR TITLE
Allow empty string for optionValuePath on fm-select

### PR DESCRIPTION
**Pull request by g-cassie**
This change makes it possible to set `optionValuePath=''` and have the entire object from the content list be set to the value of the property.  This is a very common pattern with Ember-Data.  

This behaviour was working prior to 8feb869b630361ee5038ce29b491906d66463fdf when we switched over to the built in `get` helper.  This restores the previous functionality and adds a test.

### CODE REVIEW

**Comment by g-cassie** [comment]
These failures seem to also exist on master... I think there is something going on with Ember-Try.  I noticed on @jelhan 's PRs that the builds were failing on beta - maybe this is biting us now?

**Comment by jelhan** [comment]
@g-cassie Tests are fixed in #45. Especially 8b1aef4649ccf361871837f8f4710ec740a66a88 should be necessary to get the tests running.

**Comment by Emerson** [comment]
So nice to see the green "Passing" text again – thanks @g-cassie

**Comment by g-cassie** [comment]
That was mostly @jelhan on that one.  Can you take a look at our discussion in #37 when you have a chance?  I think I will start out on that later today.

**Pull request merged**
