### PR TITLE
Observe radio group

### PR DESCRIPTION
**Pull request by jelhan**
Similar to #41, which is included in these PR.

There has been a breaking change in `optionLabelPath` and `optionValuePath`.
Before this commit they had to be prefixed by `content.`

This change has allready been made to `{{fm-select}}` in 2.1 (01913d1).

### CODE REVIEW

**Comment by jelhan** [comment]
@Emerson: I wasn't sure how to handle this breaking change. Do you think legacy support is necessary?

Made a separate PR only for `fm-select` (#41) so we haven't that one blocked by this breaking change.

**Comment by g-cassie** [comment]
@jelhan Looks good.  Only thing is that I think it might be more "ember" to pass the optionValue/Path through the template rather than using parentView property from the component which I think is discouraged.  Not sure if others have an opinion on this?

**Comment by jelhan** [comment]
Yeah of course. `optionValuePath`, `optionLabelPath` and `value` should be passed in as parameters of the `fm-radio` component. I just don't want to touch that one also. Would prefer to have some changes merged before touching more.

**Comment by Emerson** [comment]
Awesome!

**Pull request merged**
